spring:
  application:
  #应用名称
    name: moonII
  datasource:
    #连接地址
    url: jdbc:mysql://127.0.0.1/moon?characterEncoding=utf-8&useSSL=true&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2b8
    #用户名
    username: root
    #密码
    password: root
    #连接类型
    type: com.alibaba.druid.pool.DruidDataSource
server:
  #服务端口号
  port: 8083
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  health:
    status:
      order: ["DOWN","UNKNOWN","UP","OUT_OF_SERVICE"]
eureka:
  instance:
    appname: moonII
    hostname: localhost
  client:
    service-url:
     defaultZone : http://192.168.1.104:8080/eureka

